name: Print README and History

on:
  workflow_dispatch:

jobs:
  print-readme-info:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print README contents
      run: | 
        cat README.md
      working-directory: ./helloworld

    # - name: Print README commit history
    #   run: |
    #     git log --follow README.md 
    #   working-directory: ./helloworld
