name: Print README from public repo

on: 
  workflow_dispatch:

jobs:
  print-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        repository: octocat/hello-world
        ref: test


    - name: Print README
      run: cat README
      env:
        working-directory: ./hello-world
