name: Checkout my othe repo

on: 
  workflow_dispatch:

jobs:
  print-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        repository: CoderYuan/helloworld
        ref: master


    - name: Print README
      run: cat README.md
      env:
        working-directory: ./helloworld
