name: Print something

on: 
  workflow_dispatch:
  
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build artifacts
      run: |
        echo "Building artifacts for ${{ secrets.GITHUB_REPOSITORY }}"
        mkdir -p artifacts/${{ secrets.GITHUB_REPOSITORY }}
        
