name: Print something

on: 
  workflow_dispatch:
  
jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print something
      run: |
        echo "secrect: for ${{ secrets.TEST_SECRECT_1 }}"
        echo "var: ${{ vars.TEST_VAR_1 }}"
        # mkdir -p artifacts/${{ secrets.GITHUB_REPOSITORY }}
        
